"""empty message

Revision ID: a3cb74389463
Revises: 715138095db6
Create Date: 2019-05-25 11:57:31.190480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3cb74389463'
down_revision = '715138095db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('edited', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_post_edited'), 'post', ['edited'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_edited'), table_name='post')
    op.drop_column('post', 'edited')
    # ### end Alembic commands ###
